name: Travello
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_messaging: ^14.9.4
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_blue_plus: ^1.32.8
  flutter_local_notifications: ^17.1.2
  fluttertoast: ^8.2.4
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  intl: ^0.19.0
  lottie: ^3.1.0
  permission_handler: ^11.3.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/raw/splash2.json
    - lib/raw/splash3.json
    - lib/raw/splash.json
    - images/Plane.png   
    - images/preview.jpg 
    - images/People.png
    - images/Luggage.png
    - images/avatar.png
    - images/airport.png
    - images/airport2.png
    - images/Travello.png



  fonts:
    - family: ADLaMDisplay
      fonts:
        - asset: fonts/ADLaMDisplay-Regular.ttf
  